"""Export the verified prototype's patch recipe, without distributing a game EXE.

The checked-in header lets CI build the ASI without game files or Python packages.
Regeneration requires the SHA-256-verified original and a generated HUD prototype.
"""
import argparse
import hashlib
from pathlib import Path
import struct


def export(original, prototype, target):
    import pefile
    import capstone
    from .widescreen_probe import validate_image
    raw=original.read_bytes()
    digest=validate_image(raw)
    source=pefile.PE(data=raw)
    pe=pefile.PE(str(prototype))
    section=next(s for s in pe.sections if s.Name.rstrip(b'\0')==b'.hqcode')
    data=section.get_data()[:section.Misc_VirtualSize]
    magic,offset,count=struct.unpack('<8sII',data[-16:])
    if magic!=b'HQASPECT' or offset+40*count+16!=len(data):
        raise ValueError('Invalid reversible patch table')
    patches=[]
    for i in range(count):
        address,size,before,after=struct.unpack_from('<II16s16s',data,offset+i*40)
        if not 0<size<=16 or source.get_data(address-0x400000,size)!=before[:size]:
            raise ValueError('Original patch preimage mismatch')
        if pe.get_data(address-0x400000,size)!=after[:size]:
            raise ValueError('Prototype patch postimage mismatch')
        patches.append((address,size,before,after))
    def array(data): return '{'+','.join('0x%02x'%b for b in data)+'}'
    allocation_base,allocation_end=0x2200000,0x2310000
    patch_relocations=[]
    for index,(address,size,before,after) in enumerate(patches):
        if size==4 and allocation_base<=int.from_bytes(after[:4],'little')<allocation_end:
            patch_relocations.append((index,0))
        elif size>=5 and after[0] in (0xe8,0xe9):
            destination=(address+5+int.from_bytes(after[1:5],'little',signed=True))&0xffffffff
            if allocation_base<=destination<allocation_end: patch_relocations.append((index,1))
    code_address=0x400000+section.VirtualAddress
    disassembler=capstone.Cs(capstone.CS_ARCH_X86,capstone.CS_MODE_32)
    disassembler.detail=True
    code_relocations=[]
    for instruction in disassembler.disasm(data[:offset],code_address):
        at=instruction.address-code_address
        if instruction.bytes[0] in (0xe8,0xe9):
            destination=instruction.operands[0].imm&0xffffffff
            if not allocation_base<=destination<allocation_end:
                code_relocations.append((at+instruction.imm_offset,-1))
        elif instruction.imm_size==4:
            value=int.from_bytes(instruction.bytes[instruction.imm_offset:instruction.imm_offset+4],'little')
            if allocation_base<=value<allocation_end: code_relocations.append((at+instruction.imm_offset,1))
        if instruction.disp_size==4 and allocation_base<=instruction.disp<allocation_end:
            code_relocations.append((at+instruction.disp_offset,1))
    lines=['// Generated by tools/export_widescreen_patch.py; do not edit by hand.',
           '// Recipe only. No game assets or complete executable are included.',
           '#pragma once','#include <cstdint>','namespace hq::wide_recipe {',
           'struct Patch { uint32_t address, size; uint8_t before[16], after[16]; };',
           f'inline constexpr uint8_t sha256[]={array(bytes.fromhex(digest))};',
           f'inline constexpr uint32_t image_size=0x{source.OPTIONAL_HEADER.SizeOfImage:x};',
           f'inline constexpr uint32_t timestamp=0x{source.FILE_HEADER.TimeDateStamp:x};',
           f'inline constexpr uint32_t code_address=0x{0x400000+section.VirtualAddress:x};',
           'inline constexpr uint32_t allocation_base=0x2200000, allocation_size=0x110000;',
           f'inline constexpr uint8_t code[]={array(data[:offset])};',
           'inline constexpr Patch patches[]={']
    for address,size,before,after in patches:
        lines.append(f'    {{0x{address:x},{size},{array(before)},{array(after)}}},')
    lines+=['};','struct PatchRelocation { uint32_t index, offset; };',
            'inline constexpr PatchRelocation patch_relocations[]={']
    lines += [f'    {{{index},{at}}},' for index,at in patch_relocations]
    lines += ['};','struct CodeRelocation { uint32_t offset; int direction; };',
              'inline constexpr CodeRelocation code_relocations[]={']
    lines += [f'    {{{at},{direction}}},' for at,direction in code_relocations]
    lines+=['};','}','']
    target.write_text('\n'.join(lines),encoding='utf-8')
    return {'source_sha256':digest,'patches':count,'thunk_bytes':offset,
            'patch_relocations':len(patch_relocations),'code_relocations':len(code_relocations),
            'header_sha256':hashlib.sha256(target.read_bytes()).hexdigest()}


if __name__=='__main__':
    ap=argparse.ArgumentParser(description=__doc__)
    ap.add_argument('original',type=Path)
    ap.add_argument('prototype',type=Path)
    ap.add_argument('target',type=Path)
    args=ap.parse_args()
    print(export(args.original,args.prototype,args.target))
